### ISSUE TITLE
A question for Voltpillager Board

### ISSUE THREAD

**Issue by LordCasser** [zt-chen/voltpillager#1]
I'm trying to build the Voltpillager Board,but I have no idea what is J1~J7? How can I get them?

**Comment by zt-chen** [comment]
J1-J7 are just connection points. You can just use wires or some connection header such as this one: https://www.amazon.co.uk/Pack-Single-2-54-Header-Connector/dp/B06XR8CV8P/

**Comment by LordCasser** [comment]
Thanks a lot
