### ISSUE TITLE
Wrong bus drivers recommended?

### ISSUE THREAD

**Issue by Bukl198** [zt-chen/voltpillager#2]
Hi there,

I noticed that the bus drivers that are recommended by you only work in the range of vcc = 1.65v to 5.5v.

However, the operating voltage for svid bus is 1v hence there is a mismatch. Will it still work if i supplied 1.65v to the bus drivers?

Thank you.

**Comment by zt-chen** [comment]
vcc = 1.65v to 5.5v is the voltage for VCC pins. We use 3.3 in VCC pin in this design. 
As it is a open-drain driver, when the input pin is high i.e 3.3V: the output pin is floating to the voltage level of the bus(1V). When input pin is 0V, it will pull the voltage to 0V in the output pin.

**Comment by Bukl198** [comment]
Ahhh i see thank you for your explanation. Also how do I probe for the voltage of the cpu using an oscilloscope? Is there an additional pin on the VR chip that outputs the voltage? I am using the same intel NUC that you have in your research paper for reference.

**Comment by zt-chen** [comment]
The maybe a pin for voltage sensing on the VR, but the location I used is one of the big capacitors/inductors around the CPU since it's easier to solder a wire on it. Usually, there are two pins that connect the cap, one is GND the other is Vcpu.
